Ch-configure-eslint-181339558
atlp-rwanda/elites-bn-be pull request #5
Opened 2022-03-01 07:19 UTC by gihozoinnocente

# What does this PR do?
ESLint is the required linter for the project. It'll help check for style violations and flag them.

# Description of Task to be completed?
- [x]  ESLint configuration

# How should this be manually tested?
Run script yarn lint

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Any background context you want to provide?
N/A
# What are the relevant pivotal tracker stories?
[181339558]https://www.pivotaltracker.com/story/show/181339558

# Screenshots (if appropriate)

# Questions:

2022-03-01 15:01 UTC, ihonore approved these changes

2022-03-01 15:08 UTC, Dev-nkundineza approved these changes

2022-03-02 07:35 UTC, ericmaniraguha approved these changes

2022-03-02 07:39 UTC, ericmaniraguha approved these changes

2022-03-02 07:40 UTC, ericmaniraguha approved these changes

2022-03-02 07:41 UTC, ericmaniraguha approved these changes

2022-03-02 15:09 UTC, CYIMANA-Faisal requested changes
Please work on the reviews

2022-03-02 15:09 UTC, CYIMANA-Faisal commented on .editorconfig
> +root = true
I don't think this file should be pushed.

2022-03-02 15:09 UTC, CYIMANA-Faisal commented on .env
> +DB_URL_DEV=postgres://postgres:password1!@127.0.0.1:5432/gihozo
Please don't push environment variables

2022-03-02 15:09 UTC, CYIMANA-Faisal commented on .gitignore
>  node_modules
Work with honore to check the best .gitignore for this project

2022-03-02 15:09 UTC, CYIMANA-Faisal commented on .hound.yml
> +eslint:
This file should be communicating to the hound CI I cant see the houndCI doing anything

2022-03-03 06:45 UTC, ericmaniraguha approved these changes

2022-03-03 06:47 UTC, ericmaniraguha approved these changes

2022-03-03 06:48 UTC, ericmaniraguha approved these changes

2022-03-03 16:36 UTC, ericmaniraguha approved these changes

2022-03-06 17:24 UTC, merged