Circleci project setup
atlp-rwanda/elites-bn-be pull request #6
Opened 2022-03-01 18:06 UTC by niyongaboaristide17

# What does this PR do?
CircleCI is required in this project. It helps for continious integration
# Description of Task to be completed?
- [x] circleCI configuration
# How should this be manually tested?
- Click on circleCI badge in the read me
## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Any background context you want to provide?

# What are the relevant pivotal tracker stories?
- https://www.pivotaltracker.com/story/show/181339560
# Screenshots (if appropriate)

![Screenshot from 2022-03-01 20-05-21](https://user-images.githubusercontent.com/49604980/156224145-efa3316d-bcf3-4619-8bcb-baa84ddd4137.png)

2022-03-02 07:42 UTC, ericmaniraguha approved these changes

2022-03-02 15:24 UTC, CYIMANA-Faisal requested changes
Good work and please work on the reviews

2022-03-02 15:24 UTC, CYIMANA-Faisal commented on README.md
> +[![CircleCI](https://circleci.com/gh/atlp-rwanda/elites-bn-be.svg?style=svg&circle-token=f7c825d627bd711423c163f838796046bbeb5648)](https://circleci.com/gh/atlp-rwanda/elites-bn-be)
This badge should reflect to the circle CI checks

2022-03-02 15:24 UTC, CYIMANA-Faisal commented on package.json
> +      "command": "nodemon --exec babel-node ./src/app.js",
why removing npx
any reason

2022-03-02 15:24 UTC, CYIMANA-Faisal commented on package.json
> +      "command": "nyc --reporter=html --reporter=text --reporter=lcov --reporter=text-summary --check-coverage=true mocha --require @babel/register ./tests/* --timeout 1000000 --exit || true",
again can you clarify to why this line. just wondering

2022-03-02 15:24 UTC, CYIMANA-Faisal commented on src/controllers/test.controllers.js
> +export function testFunc(){
all the unit testing should be in testes

2022-03-02 15:24 UTC, CYIMANA-Faisal commented on tests/test.js
> +import chai from 'chai';
Please you have to have the same formats for the tests

2022-03-03 06:26 UTC, ericmaniraguha approved these changes

2022-03-03 08:35 UTC, closed without merging

2022-03-03 16:32 UTC, ericmaniraguha reviewed
It is fine.