Chore/#181339556-migrations-scripts-setup
atlp-rwanda/elites-bn-be pull request #8
Opened 2022-03-02 12:34 UTC by ihonore

# What does this PR do?

Adding Migration scripts to package.json 

# Description of Task to be completed?

 - Adding migration scripts
 - Adding procfile

# How should this be manually tested?

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

# Any background context you want to provide?

# What are the relevant pivotal tracker stories?

# Screenshots (if appropriate)

# Questions:

2022-03-02 15:14 UTC, CYIMANA-Faisal requested changes
Please we don't push the dist folder
it has to be generated when the CI/CD build job is finished and it has to be on server.

2022-03-02 15:18 UTC, gihozoinnocente approved these changes

2022-03-02 16:12 UTC, ihonore commented
> Please we don't push the dist folder it has to be generated when the CI/CD build job is finished and it has to be on server.

Sorry, I added it to gitignore after it was stagged and commited, now it is fixed.

2022-03-02 20:37 UTC, ericmaniraguha approved these changes

2022-03-03 06:28 UTC, ericmaniraguha approved these changes

2022-03-03 06:29 UTC, ericmaniraguha approved these changes

2022-03-03 06:36 UTC, ericmaniraguha approved these changes

2022-03-03 06:36 UTC, ericmaniraguha approved these changes

2022-03-03 16:35 UTC, ericmaniraguha approved these changes

2022-03-03 16:43 UTC, ericmaniraguha approved these changes

2022-03-03 16:43 UTC, ericmaniraguha approved these changes

2022-03-03 16:47 UTC, ericmaniraguha approved these changes

2022-03-03 16:49 UTC, ericmaniraguha approved these changes

2022-03-03 16:50 UTC, ericmaniraguha approved these changes

2022-03-03 16:54 UTC, ericmaniraguha approved these changes

2022-03-04 12:13 UTC, ericmaniraguha approved these changes

2022-03-04 12:14 UTC, ericmaniraguha approved these changes

2022-03-04 12:15 UTC, ericmaniraguha approved these changes

2022-03-04 12:16 UTC, ericmaniraguha approved these changes

2022-03-08 12:26 UTC, merged